In [17]:
import pandas as pd
import nltk
from nltk import word_tokenize, WordNetLemmatizer , pos_tag , word_tokenize
from nltk.corpus import wordnet
from nltk.corpus import stopwords
import string
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\Abdallah
[nltk_data]     Elbaz\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
data_en= pd.read_csv('../data/sentiment_data.csv')
data_ar= pd.read_csv('../data/ar_reviews_100k.tsv', sep="\t")

In [19]:
data_ar["language"]="arabic"
data_ar.drop(columns=["label"], inplace=True)

In [20]:
data_en.columns

Index(['Unnamed: 0', 'Comment', 'Sentiment'], dtype='object')

In [21]:
data_en.drop(columns=['Unnamed: 0', 'Sentiment'], inplace=True)

In [22]:
data_en.rename(columns={'Comment': 'text'}, inplace=True)

In [23]:
data_en["language"]="english"

In [24]:
data_ar=data_ar[:1000]
data_en=data_en[:1000]

In [25]:
full_data=pd.concat([data_ar,data_en], axis=0)

In [28]:
full_data

                                                  text language
860  let’s appreciate always manage put smile faces...  english
353  هذا التاريخ الذي ليس لأمة مثله هذا العالم الذي...   arabic
333  floating cities sound pretty promising free la...  english
905  كما قال آينشتاين نحن سجناء حواسنا المحددة ولا ...   arabic
289  maybe know shes audiologist annunciates everyt...  english
..                                                 ...      ...
130  coffee lovers don’t forget check cometeer save...  english
294  earplugs concerts variety frequencybalanced ea...  english
860  لا أنصح أي أحد بالأقامة في هذا الفندق السيء . ...   arabic
459  grover also lets buy products keep renting eve...  english
126  forest app phone based timer app basically set...  english

[2000 rows x 2 columns]

In [27]:
full_data=full_data.sample(frac=1, random_state=42)

In [62]:
full_data

                                                  text language
860  let’s appreciate always manage put smile faces...  english
353  هذا التاريخ الذي ليس لأمة مثله هذا العالم الذي...   arabic
333  floating cities sound pretty promising free la...  english
905  كما قال آينشتاين نحن سجناء حواسنا المحددة ولا ...   arabic
289  maybe know shes audiologist annunciates everyt...  english
..                                                 ...      ...
130  coffee lovers don’t forget check cometeer save...  english
294  earplugs concerts variety frequencybalanced ea...  english
860  لا أنصح أي أحد بالأقامة في هذا الفندق السيء . ...   arabic
459  grover also lets buy products keep renting eve...  english
126  forest app phone based timer app basically set...  english

[2000 rows x 2 columns]

In [35]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
y = full_data['language']
label = LabelEncoder()
y = label.fit_transform(y)
cv = TfidfVectorizer()
x = cv.fit_transform(full_data['text']).toarray()

In [36]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y, train_size=0.8)

In [37]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [38]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       204
           1       0.99      1.00      1.00       196

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

In [47]:
test=["شكرا"]

new_text=cv.transform(test).toarray()
prediction=model.predict(new_text)
lang=label.inverse_transform(prediction)
print(lang)

['arabic']

In [15]:
data_en= pd.read_csv('../data/sentiment_data.csv')
data_ar= pd.read_csv('../data/ar_reviews_100k.tsv', sep="\t")

In [ ]:
data_en

,Unnamed: 0,Comment,Sentiment
0,0,lets forget apple pay required brand new iphon...,1
1,1,nz retailers don’t even contactless credit car...,0
2,2,forever acknowledge channel help lessons ideas...,2
3,3,whenever go place doesn’t take apple pay doesn...,0
4,4,apple pay convenient secure easy use used kore...,2
...,...,...,...
241140,241921,crores paid neerav modi recovered congress lea...,0
241141,241922,dear rss terrorist payal gawar modi killing pl...,0
241142,241923,cover interaction forum left,1
241143,241924,big project came india modi dream project happ...,1
241144,241925,ever listen like gurukul discipline maintained...,2

In [16]:
data_en=data_en.iloc[:10,:]
data_en

   Unnamed: 0                                            Comment  Sentiment
0           0  lets forget apple pay required brand new iphon...          1
1           1  nz retailers don’t even contactless credit car...          0
2           2  forever acknowledge channel help lessons ideas...          2
3           3  whenever go place doesn’t take apple pay doesn...          0
4           4  apple pay convenient secure easy use used kore...          2
5           5  we’ve hounding bank adopt apple pay understand...          1
6           6    got apple pay south africa it’s widely accepted          2
7           7                need apple pay physical credit card          1
8           8  united states abundance retailers accept apple...          2
9           9  cambodia universal qr code system scan send mo...          1

In [ ]:
import pickle

# Save the model
with open('../models/model_lnguage_categorize.pkl', 'wb') as file:
    pickle.dump(model, file)

In [51]:
with open('../models/vectorizer_lnguage_categorize.pkl', 'wb') as file:
    pickle.dump(cv, file)

In [52]:
with open('../models/LE_lnguage_categorize.pkl', 'wb') as file:
    pickle.dump(label, file)

In [50]:
with open('../models/model_lnguage_categorize.pkl', 'rb') as file:
    loaded_model = pickle.load(file)